version: "3.9"

services:
  backend:
    image: academyacrj3r5dv.azurecr.io/team3-back-app:latest
    ports:
      - "3001:3001"
    env_file:
      - .env

  frontend:
    image: academyacrj3r5dv.azurecr.io/team3-front-app:latest
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://backend:3001
    depends_on:
      - backend

  postgres:
    image: academyacrj3r5dv.azurecr.io/team3-postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  