name: CI Pipeline
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '25.5.0'

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma client
        run: npm run ci:generate

      - name: Build project
        run: npm run ci:build

      - name: Run tests
        run: npm run test

      - name: Run Linter
        run: npm run lint

      - name: Login to Azure Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }} # e.g. myregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image to ACR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/team3-back-app:${{ github.sha }} .
          docker tag ${{ secrets.ACR_LOGIN_SERVER }}/team3-back-app:${{ github.sha }} ${{ secrets.ACR_LOGIN_SERVER }}/team3-back-app:latest
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/team3-back-app:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/team3-back-app:latest